[task]
mode = "ur"
num_client = 1
num_worker = 0

[multicast]
ip = "127.0.0.255"
variant = "halfsiphash"

[[replica]]
control-host = "127.0.0.1"
host = "127.0.0.1"
link-address = "aa:aa:aa:00:00:01"
dev-port = 0

[[replica]]
control-host = "127.0.0.2"
host = "127.0.0.2"
link-address = "aa:aa:aa:00:00:02"
dev-port = 4

[[replica]]
control-host = "127.0.0.3"
host = "127.0.0.3"
link-address = "aa:aa:aa:00:00:03"
dev-port = 8

[[replica]]
control-host = "127.0.0.4"
address = "127.0.0.4"
link-address = "aa:aa:aa:00:00:04"
dev-port = 12

[[client]]
control-host = "127.0.0.101"
host = "127.0.0.101"
link-address = "bb:bb:bb:00:00:01"
dev-port = 32
